# Generated by Django 5.0.4 on 2024-10-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'お知らせ', 'verbose_name_plural': 'お知らせリスト'},
        ),
    ]
